[package]
name = "vulkan-learning"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
log = "0.4"
env_logger = "0.11.8"
vulkanalia = { version = "=0.28.0", features = ["libloading", "provisional", "window"] }
winit = "0.30.9"
